### ISSUE TITLE
Choose color palette

### ISSUE THREAD

**Issue by benmaier** [ulfaslak/network_styling_with_d3#17]
the color palette for groups should be choosable somehow (feature for later)

**Comment by ulfaslak** [comment]
This is almost a feature already. I wanted the interaction for choosing color to be as simple as possible, so I made group-colors continuously change when the node color is changed. It looks quite cool actually and making it work was a little complicated so maybe I'm too happy with it compared to the confusion it creates, but as it stands you are able to change group colors, just not exactly as you like. THAT SAID, if the group name is a string that matches a known color (like "red" or "#e74c3c") then the nodes will have that color.

**Comment by benmaier** [comment]
ah wow, I did not know this. Can you write a short paragraph highlighting this feature in the docs?

**Comment by ulfaslak** [comment]
Will do
