### ISSUE TITLE
Feature request: quick load network with `?<linkaddress>` url ending

### ISSUE THREAD

**Issue by ulfaslak** [ulfaslak/network_styling_with_d3#2]

**Comment by benmaier** [comment]
solved in #10 , usage `?data=url`, e.g.

`http://network-styling-url.domain/?data=https://gist.githubusercontent.com/ulfaslak/6be66de1ac3288d5c1d9452570cbba5a/raw/0b9595c09b9f70a77ee05ca16d5a8b42a9130c9e/miserables.json`

**Comment by ulfaslak** [comment]
There was a minor issue (both data and config had to be specified) which I fixed. Now it works
