### ISSUE TITLE
custom config options not adopted to GUI

### ISSUE THREAD

**Issue by benmaier** [ulfaslak/network_styling_with_d3#23]
I just tried iterating some layout options but the config does not seem to be updated to the GUI. (it does, however, seem to be be applied. besides the "display node labels" option, which does not seem to work).

code:

```python
import numpy as np
from netwulf import visualize
import networkx as nx

G = nx.barabasi_albert_graph(100,1)

config = {
    'node_stroke_color': '#fff',
    'node_fill_color': '#79aaa0',
    'node_label_color': '#000000',
    'link_color': '#758086',
    'node_collision': True,
    'node_gravity': 0.01,
    'node_charge': -120,
    'node_size': 5,
    'scale_node_size_by_strength': True,
     'link_width': 2,
     'zoom':3,
     'display_node_labels': False,
}
visualize(G,config=config)
```

<img width="1370" alt="Screen Shot 2019-05-20 at 11 40 03" src="https://user-images.githubusercontent.com/10728380/58012357-92804700-7af4-11e9-9b28-e527f5d0c8fa.png">

**Comment by benmaier** [comment]
lol i'm dumb. disregard pls

**Comment by ulfaslak** [comment]
nice layout tho
