### ISSUE TITLE
Fetch local file

### ISSUE THREAD

**Issue by jct94** [ulfaslak/network_styling_with_d3#28]
Hey Ulf, was playing around with ur repo, great tool.
I was just wondering how to replace the gisturl by a local graph.json file, I tried to fetch a local path but it says "file not found", do you have a workaround ? I do not know where the error comes from.
Cheers

**Comment by ulfaslak** [comment]
Hmm... I don't know but it works for me. What steps are you following here?

So if I (1) clone the repo (2) `cd network_styling_with_d3` (3) `python -m http.server 8000` (4) go to `localhost:8000?url=/path/to/my/graph` it works.

**Comment by jct94** [comment]
I was trying to change the path within vis.js 
`  if (controls['file_path'] == "") controls['file_path'] = "yourgistlink";`

it works with a gist, but not with local file

**Comment by ulfaslak** [comment]
Ah ok. Well, try no changing the code but just inputting the path as a url argument (step 4 above). That should work.

**Comment by jct94** [comment]
It does, thanks!
